# Generated by Django 5.1 on 2024-08-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
