# Generated by Django 5.1 on 2024-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium_service",
            "0002_alter_ticket_options_alter_ticket_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="showtheme",
            field=models.ManyToManyField(
                blank=True,
                related_name="showthemes",
                to="planetarium_service.showtheme",
            ),
        ),
        migrations.AddField(
            model_name="showtheme",
            name="astronomyshow",
            field=models.ManyToManyField(
                blank=True,
                related_name="astronomyshows",
                to="planetarium_service.astronomyshow",
            ),
        ),
    ]
