# Generated by Django 5.1 on 2024-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_service", "0003_alter_astronomyshow_options_and_more"),
        ("planetarium_service", "0004_rename_astronomy_show_showsession_astronomyshow"),
    ]

    operations = []
